### ISSUE TITLE
some url not work

### ISSUE THREAD

**Issue by xibr** [UserGhost411/instagram-downloader-php#3]
hi, this link not work

`https://www.instagram.com/p/BzdNYr1lNXq/?igshid=60zku01rynd5`

download url

`https://static.cdninstagram.com/rsrc.php/null.jpg?dl=1`

**Comment by UserGhost411** [comment]
Done , issue fixed 
https://github.com/UserGhost411/instagram-downloader-php/commit/1be421dca1ca82a4feb70b54febd770429b24560

**Comment by xibr** [comment]
thanks, but if the post link have more video like this [https://www.instagram.com/p/ByN54nvJrId/](url) 
return only one video
![insta](https://user-images.githubusercontent.com/20098154/63637625-5e866600-c68f-11e9-8915-fbf8cc6ff242.JPG)

**Comment by UserGhost411** [comment]
Done , now you can download multiple Video
https://github.com/UserGhost411/instagram-downloader-php/commit/5d6642e9713b6209c18a5c77d4b299c7f4e5305d Fixed
